apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-publish
spec:
  template:
    spec:
      containers:
        - name: rabbitmq-client
          image: 146917/keda-rabbitmq-example:latest
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-connection-secret
                  key: RABBITMQ_CONNECTION_STRING
          command: ['send', '$(RABBITMQ_CONNECTION)', '300']
      restartPolicy: Never
  backoffLimit: 4
